### ISSUE TITLE
Use semantic release?

### ISSUE THREAD

**Issue by ColinEberhardt** [rollup/rollup-plugin-wasm#4]
Hi @jamen would you mind if I enable semantic release and add a CI build to this repo?

With semantic release, any merged commits are automatically released to npm, and version numbers incremented based on a simple set of rules around the commit messages.

https://github.com/semantic-release/semantic-release

**Comment by jamen** [comment]
@ColinEberhardt That sounds good to me.  :+1:

**Comment by ColinEberhardt** [comment]
Cool - I've pushed the required config changes https://github.com/rollup/rollup-plugin-wasm/commit/5331a5888b53b79387ff2c85bd3c61911e8138b7

(I didn't bother with a pull request on this one as it's just config - for any other changes, I'll go via PR / review!)
